### ISSUE TITLE
User experience: playthrough of one turn

### ISSUE THREAD

**Issue by yurigotskoff** [chorhatarahuduketuri/gc#10]
Tie down a solid walkthrough of one gameplay turn. Confirm and go through on Sunday

**Comment by adrianlshaw** [comment]
@chorhatarahuduketuri  I concur.

**Comment by chorhatarahuduketuri** [comment]
This is so generic as to be considered already implemented, and therefore I'm closing it. 

I think we should decide on Sunday what the MVP for turn is going to be.
