### ISSUE TITLE
Separate player and non-player access to control of units

### ISSUE THREAD

**Issue by chorhatarahuduketuri** [chorhatarahuduketuri/gc#38]
Let the human player control only one factions units, and disallow them from accessing information about or controlling the units of other factions. 

This is a necessary prerequisite of #5 , as the AI requires the same access controls. 

I don't know if this ties in to how the human player has the screen rendered for them, with regards to #9 .
How to restrict the AI players perception of the game space is unknown at this time.

**Comment by chorhatarahuduketuri** [comment]
Being worked on in branch feature/separate_players

**Comment by adrianlshaw** [comment]
Can this be closed now? Was introduced in #40

**Comment by chorhatarahuduketuri** [comment]
Yes it can. There is still a bug where a human can get the orders context menu up for AI players, but it doesn't do anything.
