### ISSUE TITLE
GalaxyView.java needs cleaning up

### ISSUE THREAD

**Issue by chorhatarahuduketuri** [chorhatarahuduketuri/gc#43]
We've been casually adding things to GalaxyView.java in an unplanned way, and it's gotten to be quite a mess, particularly with passing object references around (this has only become such a significant issue due to the recent refactoring). 

This class needs to be tidied up and access to fields in other classes and objects restricted via getter/setter methods and the narrowest access scope possible (private by default).

**Comment by adrianlshaw** [comment]
Couldn't agree more, it's been on my mind.

**Comment by chorhatarahuduketuri** [comment]
Has this been completed?

**Comment by chorhatarahuduketuri** [comment]
Has this been completed @adrianlshaw ?

**Comment by adrianlshaw** [comment]
I think we’ve done what’s possible for now. If it becomes a problem again then let’s re-open the issue.
