### ISSUE TITLE
This needs an amazing AI player

### ISSUE THREAD

**Issue by adrianlshaw** [chorhatarahuduketuri/gc#5]
No AI player. Need something amazing.

**Comment by chorhatarahuduketuri** [comment]
This requires a separation of control between the player and the computer. 

There must be `units` that the player can control, and `units` that the player cannot control, based on the `faction`. When the turn is being processed, the computer can then make decisions for all units from factions that aren't the one the player is playing.

**Comment by adrianlshaw** [comment]
@chorhatarahuduketuri I think we can close this one now? :)
