### ISSUE TITLE
Starting and ending games

### ISSUE THREAD

**Issue by chorhatarahuduketuri** [chorhatarahuduketuri/gc#66]
- [x] Start new game
- [x] Win game when everyone else is dead
- [x] Lose game when you're dead

**Comment by adrianlshaw** [comment]
Let's elaborate what a dead player really means: when a player has lost control of all their systems? Or all units and systems?

**Comment by chorhatarahuduketuri** [comment]
For MVP, I'd define it as having no systems. That's simple. 

For later, I'd have a more complex system where it determines the physical possibility of winning, and you only lose once that's gone, probably when your last colony and colony ships are destroyed, or maybe something more complex.
