### ISSUE TITLE
Global data structure access

### ISSUE THREAD

**Issue by adrianlshaw** [chorhatarahuduketuri/gc#8]
Shall we move the game data structures out of the GalaxyView, and if so then where? Note that the GalaxyView will still need up to date access to them in order to paint appropriately. The code would be better off this way. The view, the AI and the player will need to be able to have access to this with well defined interfaces, so makes sense to have a separate class.

**Comment by chorhatarahuduketuri** [comment]
I feel this issue is out of date, so I'm closing it.
