### ISSUE TITLE
Repo should contain an apk for install

### ISSUE THREAD

**Issue by chorhatarahuduketuri** [chorhatarahuduketuri/gc#89]
As per title, this should be part of version 2 (probably one of it's defining features over version 1).

**Comment by adrianlshaw** [comment]
The typical Github way of hosting binary releases (things like installers etc, in this case, APKs) is to use the following:
https://help.github.com/articles/creating-releases/

**Comment by adrianlshaw** [comment]
@chorhatarahuduketuri read these instructions: https://blog.fossasia.org/push-your-apk-to-your-github-repository-from-travis/

**Comment by adrianlshaw** [comment]
This is now completed.
